from dma.core import RetrievalStep, EntityQuery, EmbeddingQuery, RetrievalQuery, Retrieval
from dma.core import Conversation, Message
from dma.core import Memory, MemoryResult

from .graph import GraphMemory, Neo4jMemory

from dma.config.dma_config import get_config

class Retriever:
    """A retriever is responsible for fetching relevant information from memory
    based on the queries generated by the pipeline.
    It uses the graph database and vector database to retrieve information.
    
    At also allows new memories to be added to the memory.
    """
    
    def __init__(self):
        self.config = get_config()
        
        # TODO: initialize actual memory backend
        self.graph_memory = Neo4jMemory()
        
        
    def add_memory(self, memory: Memory):
        raise NotImplementedError("Method not implemented yet.")
    
    def add_memories(self, memories: list[Memory]):
        # might be useful to add in batch for efficiency
        raise NotImplementedError("Method not implemented yet.")
    
    def add_memory_series(self, memories: list[Memory]):
        """Add a series of memories to the memory backend.
        Memories in a series are linked together in order.
        
        Parameters
        ----------
        memories : list[Memory]
            The list of memory objects to add.
        
        Returns
        -------
        bool
            True if the memories were added successfully, False otherwise.
        """
        raise NotImplementedError("Method not implemented yet.")
    
    def retrieve(self, query: RetrievalStep, top_k: int = 5) -> list[MemoryResult]:
        """Retrieve relevant memories based on the provided query.
        
        Parameters
        ----------
        query : RetrievalStep
            The retrieval step containing the queries.
        top_k : int
            The number of top results to retrieve.
        
        Returns
        -------
        list[Memory]
            A list of retrieved memories.
        """
        return []  # not implemented yet