from dma.core import RetrievalStep, EntityQuery, EmbeddingQuery, RetrievalQuery, Retrieval
from dma.core import Conversation, Message
from dma.core import Memory, MemoryResult

from .graph import GraphMemory, Neo4jPlaceholder
from .vector import VectorMemory, FaissPlaceholder

from dma.config.dma_config import get_config

class Retriever:
    """A retriever is responsible for fetching relevant information from memory
    based on the queries generated by the pipeline.
    It uses the graph database and vector database to retrieve information.
    
    At also allows new memories to be added to the memory.
    """
    
    def __init__(self):
        self.config = get_config()
        
        # TODO: initialize actual memory backends here
        self.graph_memory: GraphMemory = Neo4jPlaceholder()
        self.vector_memory: VectorMemory = FaissPlaceholder()
        
    def add_memory(self, memory: Memory):
        raise NotImplementedError("Method not implemented yet.")
    
    def add_memories(self, memories: list[Memory]):
        # might be useful to add in batch for efficiency
        raise NotImplementedError("Method not implemented yet.")
    
    def retrieve(self, query: RetrievalStep, top_k: int = 5) -> list[MemoryResult]:
        """Retrieve relevant memories based on the provided query.
        
        Parameters
        ----------
        query : RetrievalStep
            The retrieval step containing the queries.
        top_k : int
            The number of top results to retrieve.
        
        Returns
        -------
        list[Memory]
            A list of retrieved memories.
        """
        raise NotImplementedError("Method not implemented yet.")