from dma.core import RetrievalStep, EntityQuery, EmbeddingQuery, RetrievalQuery, Retrieval
from dma.core import Conversation, Message
from dma.core import Memory, MemoryResult

from .graph import Neo4jMemory, GraphMemory

from dma.config.dma_config import get_config

class Retriever:
    """A retriever is responsible for fetching relevant information from memory
    based on the queries generated by the pipeline.
    It uses the graph database and vector database to retrieve information.
    
    At also allows new memories to be added to the memory.
    """
    
    def __init__(self):
        self.config = get_config()
        
        self.graph_memory: GraphMemory = Neo4jMemory()
        
        
    def add_memory(self, memory: Memory) -> bool:
        """Add a single memory to the memory backend.
        
        Parameters
        ----------
        memory : Memory
            The memory object to add.
            
        Returns
        -------
        bool
            True if the memory was added successfully, False otherwise.
        """
        return self.graph_memory.add_memory(memory)

    def add_memory_batch(self, memories: list[Memory]) -> list[str]:
        """Add a batch of memories to the memory backend.
        
        Parameters
        ----------
        memories : list[Memory]
            The list of memory objects to add.

        Returns
        -------
        list[str]
            A list of IDs for the added memories.
        """
        return self.graph_memory.add_memory_batch(memories)

    def add_memory_series(self, memories: list[Memory]) -> bool:
        """Add a series of memories to the memory backend.
        Memories in a series are linked together in order.

        Parameters
        ----------
        memories : list[Memory]
            The list of memory objects to add.
        
        Returns
        -------
        bool
            True if the memories were added successfully, False otherwise.
        """
        return self.graph_memory.add_memory_series(memories)
    
    def retrieve(self, query: RetrievalStep, top_k: int = 5) -> list[MemoryResult]:
        """Retrieve relevant memories based on the provided query.
        
        Parameters
        ----------
        query : RetrievalStep
            The retrieval step containing the queries.
        top_k : int
            The number of top results to retrieve.
        
        Returns
        -------
        list[Memory]
            A list of retrieved memories.
        """
        return []  # not implemented yet